#!/bin/bash
# call this script to start your flask server and data collection

# change into the app directory
cd /home/byte/graphr
# run the data collection script
nohup python poll_verdi.py &
# run the server and pipe the output to a log file
gunicorn -D -w 4 -p server.pid -b 0.0.0.0:9999 app:app 
